### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by hitecjunkie** [felipeelia/cf7-repeatable-fields#36]

**Comment by felipeelia** [comment]
@hitecjunkie I know this is one thousand years old already but I'm trying to get back to the plugin now. Do you happen to remember how to trigger this warning? Thanks!

**Comment by felipeelia** [comment]
As we didn’t have any movement on this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
