### ISSUE TITLE
Getting “One or more fields have an error. Please check and try again.”

### ISSUE THREAD

**Issue by bhartii18** [felipeelia/cf7-repeatable-fields#67]
### Describe your question

I am getting this error while click on submit (One or more fields have an error. Please check and try again.), when i remove your code it works fine. How to fix this issue in wordpress website?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@bhartii18 I will need the contents of your Form and Mail tabs to help you.

**Comment by felipeelia** [comment]
As we didn’t have any movement on this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
